cache: pip
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"

env:
  - SPHINX_SPEC='sphinx~=2.4.0'
  - SPHINX_SPEC='sphinx~=3.0.0'
  # latest release
  - SPHINX_SPEC='sphinx'
  # master branch (in development)
  - SPHINX_SPEC='git+https://github.com/sphinx-doc/sphinx.git#egg=Sphinx'

matrix:
  allow_failures:
  - env: SPHINX_SPEC='git+https://github.com/sphinx-doc/sphinx.git#egg=Sphinx'

install:
  - pip install coveralls sphinx_rtd_theme "${SPHINX_SPEC}"
  - python setup.py install

script:
  - coverage run --source=hieroglyph setup.py test
  - cd docs; READTHEDOCS=True SPHINXOPTS="-NqW" SPHINXBUILD="sphinx-build" make -e clean html slides; cd ..

after_success:
  - coveralls
